// <auto-generated />
using System;
using ClinicaEnza.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaEnza.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921200542_InicialTPH")]
    partial class InicialTPH
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ClinicaEnza.Domain.Consultorio", b =>
                {
                    b.Property<int>("IdConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Piso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdConsultorio");

                    b.ToTable("Consultorios", (string)null);
                });

            modelBuilder.Entity("ClinicaEnza.Domain.HistoriaClinica", b =>
                {
                    b.Property<int>("IdHistoriaClinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdHistoriaClinica");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("HistoriasClinicas", (string)null);
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPersona");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);

                    b.HasDiscriminator<string>("TipoPersona").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ClinicaEnza.Domain.PrescripcionMedica", b =>
                {
                    b.Property<int>("IdPrescripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdHistoriaClinica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMedico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("IdPrescripcion");

                    b.HasIndex("IdHistoriaClinica");

                    b.HasIndex("IdMedico");

                    b.ToTable("PrescripcionesMedicas", (string)null);
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdConsultorio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMedico")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdConsultorio", "Horario");

                    b.HasIndex("IdMedico", "Horario");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Medico", b =>
                {
                    b.HasBaseType("ClinicaEnza.Domain.Persona");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Medico");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Paciente", b =>
                {
                    b.HasBaseType("ClinicaEnza.Domain.Persona");

                    b.Property<decimal>("Altura")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObraSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Peso")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Usuario", b =>
                {
                    b.HasBaseType("ClinicaEnza.Domain.Persona");

                    b.Property<DateTime>("FechaInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.ToTable("Personas", t =>
                        {
                            t.Property("FechaInicio")
                                .HasColumnName("Usuario_FechaInicio");
                        });

                    b.HasDiscriminator().HasValue("Usuario");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.HistoriaClinica", b =>
                {
                    b.HasOne("ClinicaEnza.Domain.Paciente", "Paciente")
                        .WithOne("HistoriaClinica")
                        .HasForeignKey("ClinicaEnza.Domain.HistoriaClinica", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.PrescripcionMedica", b =>
                {
                    b.HasOne("ClinicaEnza.Domain.HistoriaClinica", "HistoriaClinica")
                        .WithMany("Prescripciones")
                        .HasForeignKey("IdHistoriaClinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaEnza.Domain.Medico", "Medico")
                        .WithMany("Prescripciones")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Turno", b =>
                {
                    b.HasOne("ClinicaEnza.Domain.Consultorio", "Consultorio")
                        .WithMany("Turnos")
                        .HasForeignKey("IdConsultorio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEnza.Domain.Medico", "Medico")
                        .WithMany("Turnos")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicaEnza.Domain.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Consultorio", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.HistoriaClinica", b =>
                {
                    b.Navigation("Prescripciones");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Medico", b =>
                {
                    b.Navigation("Prescripciones");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("ClinicaEnza.Domain.Paciente", b =>
                {
                    b.Navigation("HistoriaClinica");

                    b.Navigation("Turnos");
                });
#pragma warning restore 612, 618
        }
    }
}
